[package]
name = "ncurses_chip8"
version = "0.1.0"
authors = ["Jayson Reis <santosdosreis@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "*"
env_logger = "*"
log = "*"
ncurses = "*"
enum-primitive-derive = "0.1.2"
num-traits = "0.2.10"
